wallpaper {
    monitor = eDP-1
    path = /home/toby/.config/hypr/wallpaper/blackwolfshadow1-wolf-of-the-night.jpg
    fit_mode = cover
}

wallpaper {
    monitor = *
    path = /home/toby/.config/hypr/wallpaper/blackwolfshadow1-wolf-of-the-night.jpg
    fit_mode = cover
}

ipc = on
splash = false
